id: 252fa1e652f8426b9ac7a87de401b892
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_100-The_Ornament_of_the_Light_of_Awareness-v1
  language: bo
  author: ''
  volume: {}
